document.write('\
<option value="p"                           >Pressure (Pa)</option>\
<option value="rho"                         >Density (kg/m3)</option>\
<option value="u"                           >W-E wind component (m/s)</option>\
<option value="v"                           >S-N wind component (m/s)</option>\
<option value="wind"                        >Horizontal wind speed (m/s)</option>\
<option value="zradius"                     >Radial distance from planet center (m)</option>\
<option value="zareoid"                     >Altitude above areoid (Mars geoid) (m)</option>\
<option value="zsurface"                    >Altitude above local surface (m)</option>\
<option value="oroheight"                   >Orographic height (m) (surface altitude above areoid)</option>\
<option value="oro_gcm"                     >GCM orography (m)</option>\
<option value="theta_s"                     >Local slope inclination (deg) (HR mode only)</option>\
<option value="psi_s"                       >Local slope orientation (deg) (HR mode only)</option>\
<option value="marsau"                      >Sun-Mars distance (in Astronomical Unit AU)</option>\
<option value="ls"                          >Ls, solar longitude of Mars (deg)</option>\
<option value="loctime"                     >LST:Local true solar time (hrs)</option>\
<option value="lmeantime"                   >LMT:Local mean time (hrs) at sought longitude</option>\
<option value="utime"                       >Universal solar time (LST at lon=0) (hrs)</option>\
<option value="solzenang"                   >Solar zenith angle (deg)</option>\
<option value="tsurf"                       >Surface temperature (K)</option>\
<option value="ps"                          >Surface pressure (Pa)</option>\
<option value="ps_gcm"                      >GCM surface pressure (Pa)</option>\
<option value="potential_temp"              >Potential temperature (K) (reference pressure=610Pa)</option>\
<option value="w_l"                         >Vertical wind component (m/s) (Up-Down)</option>\
<option value="zonal_slope_wind"            >Zonal slope wind component (m/s) (HR mode only)</option>\
<option value="merid_slope_wind"            >Meridional slope wind component (m/s) (HR mode only)</option>\
<option value="rmsps"                       >Surface pressure RMS day to day variations (Pa)</option>\
<option value="rmstsurf"                    >Surface temperature RMS day to day variations (K)</option>\
<option value="altrmsp"                     >Atmospheric pressure RMS day to day variations (Pa)</option>\
<option value="rmsrho"                      >Density RMS day to day variations (kg/m^3)</option>\
<option value="rmst"                        >Temperature RMS day to day variations (K)</option>\
<option value="rmsu"                        >Zonal wind RMS day to day variations (m/s)</option>\
<option value="rmsv"                        >Meridional wind RMS day to day variations (m/s)</option>\
<option value="rmsw"                        >Vertical wind RMS day to day variations (m/s)</option>\
<option value="fluxtop_dn_sw"               >Incident solar flux at top of the atmosphere (W/m2)</option>\
<option value="fluxtop_up_sw"               >solar flux reflected to space (W/m2)</option>\
<option value="fluxsurf_dn_sw"              >Incident solar flux on horizontal surface (W/m2)</option>\
<option value="fluxsurf_dn_sw_hr"           >Incident solar flux on local slope (W/m2) (HR mode only)</option>\
<option value="fluxsurf_up_sw"              >Reflected solar flux on horizontal surface (W/m2)</option>\
<option value="fluxtop_lw"                  >thermal IR flux to space (W/m2)</option>\
<option value="fluxsurf_lw"                 >thermal IR flux on surface (W/m2)</option>\
<option value="z_0"                         >GCM surface roughness length z0 (m)</option>\
<option value="thermal_inertia"             >GCM surface thermal inertia</option>\
<option value="ground_albedo"               >GCM surface bare ground albedo</option>\
<option value="dod"                         >Monthly mean dust column visible optical depth</option>\
<option value="tauref"                      >Daily mean dust column visible optical depth</option>\
<option value="dust_mmr"                    >Dust mass mixing ratio (kg/kg)</option>\
<option value="dust_reff"                   >Dust effective radius (m)</option>\
<option value="dust_dep"                    >Daily mean dust deposition rate (kg m-2 s-1)</option>\
<option value="co2ice"                      >Monthly mean surface CO2 ice layer (kg/m2)</option>\
<option value="surf_h2o_ice"                >Monthly mean surface H2O layer (kg/m2)</option>\
<option value="water_cap"                   >GCM perennial surface water ice (0 or 1)</option>\
<option value="col_h2ovapor"                >Water vapor column (kg/m2)</option>\
<option value="vmr_h2o"                     >Water vapor vol. mixing ratio (mol/mol)</option>\
<option value="col_h2oice"                  >Water ice column (kg/m2)</option>\
<option value="vmr_h2oice"                  >Water ice mixing ratio (mol/mol)</option>\
<option value="h2oice_reff"                 >Water ice effective radius (m)</option>\
<option value="zmax"                        >Convective Planetary Boundary Layer (PBL) height (m)</option>\
<option value="wstar_up"                    >Max. upward convective wind within the PBL (m/s)</option>\
<option value="wstar_dn"                    >Max. downward convective wind within the PBL (m/s)</option>\
<option value="vvv"                         >Convective vertical wind variance at level z (m2/s2)</option>\
<option value="vhf"                         >Convective eddy vertical heat flux at level z (m/s/K)</option>\
<option value="surfstress"                  >Surface wind stress (kg/m/s2)</option>\
<option value="sensib_flux"                 >Surface sensible heat flux (W/m2)</option>\
<option value="Cp"                          >Air heat capacity Cp (J kg-1 K-1)</option>\
<option value="gamma"                       >Ratio of specific heats Cp/Cv</option>\
<option value="Rgas"                        >Molecular gas constant R (J K-1 kg-1)</option>\
<option value="viscosity"                   >Air viscosity estimation (N s m-2)</option>\
<option value="pscaleheight"                >Scale height H(p) (m)</option>\
<option value="vmr_co2"                     >[CO2] volume mixing ratio (mol/mol)</option>\
<option value="vmr_n2"                      >[N2] volume mixing ratio  (mol/mol)</option>\
<option value="vmr_ar"                      >[Ar] volume mixing ratio  (mol/mol)</option>\
<option value="vmr_co"                      >[CO] volume mixing ratio  (mol/mol)</option>\
<option value="vmr_o"                       >[O] volume mixing ratio   (mol/mol)</option>\
<option value="vmr_o2"                      >[O2] volume mixing ratio  (mol/mol)</option>\
<option value="vmr_o3"                      >[O3] volume mixing ratio  (mol/mol)</option>\
<option value="vmr_h"                       >[H] volume mixing ratio   (mol/mol)</option>\
<option value="vmr_h2"                      >[H2] volume mixing ratio  (mol/mol)</option>\
<option value="vmr_he"                      >[He] volume mixing ratio  (mol/mol)</option>\
<option value="col_co2"                     >CO2 column (kg/m2)</option>\
<option value="col_n2"                      >N2 column  (kg/m2)</option>\
<option value="col_ar"                      >Ar column  (kg/m2)</option>\
<option value="col_co"                      >CO column  (kg/m2)</option>\
<option value="col_o"                       >O column   (kg/m2)</option>\
<option value="col_o2"                      >O2 column  (kg/m2)</option>\
<option value="col_o3"                      >O3 column  (kg/m2)</option>\
<option value="col_h"                       >H column   (kg/m2)</option>\
<option value="col_h2"                      >H2 column  (kg/m2)</option>\
<option value="col_he"                      >He column  (kg/m2)</option>\
<option value="vmr_elec"                    >Electron number density (particules/cm3)</option>\
<option value="col_elec"                    >Total electonic content (TEC) (particules/m2)</option>\
');
