document.write('\
<option value="p"             >Pressure (Pa)</option>\
<option value="rho"           >Density (kg/m3)</option>\
<option value="wind"          >Horizontal wind (m/s)</option>\
<option value="w"             >Vertical wind (m/s, pos. when downward)</option>\
<option value="u"             >W-E wind component (m/s)</option>\
<option value="v"             >S-N wind component (m/s)</option>\
<option value="tsurf"         >Surface temperature (K)</option>\
<option value="ps"            >Surface pressure (Pa)</option>\
<option value="tau"           >Dust column vis opt depth above surf</option>\
<option value="qdust"         >Dust mass mixing ratio (kg/kg)</option>\
<option value="rdust"         >Dust effective radius (m)</option>\
<option value="sdust"         >Dust deposition on flat surface (kg/m2/s)</option>\
<option value="mtot"          >Water vapor column (kg/m2)</option>\
<option value="icetot"        >Water cloud ice column (kg/m2)</option>\
<option value="h2ovap"        >Water vapor vol. mixing ratio (mol/mol)</option>\
<option value="h2oice"        >Water ice mixing ratio (mol/mol)</option>\
<option value="co2ice"        >surface CO2 ice layer (kg/m2)</option>\
<option value="groundice"     >surface H2O ice layer (kg/m2, 0.5: perennial)</option>\
<option value="pbl"           >Convective PBL height (m)</option>\
<option value="stress"        >Surf. wind stress (Kg/m/s2)</option>\
<option value="updraft"       >Max PBL updraft wind (m/s)</option>\
<option value="downdraft"     >Max PBL downdraft wind (m/s)</option>\
<option value="pblwvar"       >PBL vert wind variance (m2/s2)</option>\
<option value="pblhvar"       >PBL eddy vert heat flux (m/s/K)</option>\
<option value="ps_ddv"        >Surf. pres. day to day variability (Pa)</option>\
<option value="p_ddv"         >Pressure day to day variability (Pa)</option>\
<option value="t_ddv"         >Temperature day to day variability (K)</option>\
<option value="rho_ddv"       >density day to day variability (kg/m^3)</option>\
<option value="tau_ddv"       >Dust column day to day variability</option>\
<option value="tsurfmx"       >daily max mean surf temperature (K)</option>\
<option value="tsurfmn"       >daily min mean surf temperature (K)</option>\
<option value="lwdown"        >thermal IR flux to surface (W/m2)</option>\
<option value="swdown"        >solar flux to surface (W/m2)</option>\
<option value="lwup"          >thermal IR flux to space (W/m2)</option>\
<option value="swup"          >solar flux reflected to space (W/m2)</option>\
<option value="co2col"        >CO2 column (kg/m2)</option>\
<option value="arcol"         >Ar column (kg/m2)</option>\
<option value="n2col"         >N2 column (kg/m2)</option>\
<option value="cocol"         >CO column (kg/m2)</option>\
<option value="o3col"         >O3 column (kg/m2)</option>\
<option value="co2"           >[CO2] vol. mixing ratio (mol/mol)</option>\
<option value="ar"            >[Ar] vol. mixing ratio (mol/mol)</option>\
<option value="n2"            >[N2] vol. mixing ratio (mol/mol)</option>\
<option value="co"            >[CO] vol. mixing ratio (mol/mol)</option>\
<option value="o3"            >[O3] ozone vol. mixing ratio (mol/mol)</option>\
<option value="o"             >[O] vol. mixing ratio (mol/mol)</option>\
<option value="o2"            >[O2] vol. mixing ratio (mol/mol)</option>\
<option value="hydro"         >[H] vol. mixing ratio (mol/mol)</option>\
<option value="hydro2"        >[H2] vol. mixing ratio (mol/mol)</option>\
<option value="e"             >electron number density (cm-3)</option>\
<option value="ecol"          >Total Electronic Content (TEC) (m-2)</option>\
<option value="cp"            >Air heat capacity Cp (J kg-1 K-1)</option>\
<option value="visc"          >Air viscosity estimation (N s m-2)</option>\
');
