document.write('\
<option value="p"             >Pressure (Pa)</option>\
<option value="rho"           >Density (kg/m3)</option>\
<option value="wind"          >Horizontal wind (m/s)</option>\
<option value="w"             >Vertical wind (m/s, pos. when upward)</option>\
<option value="u"             >W-E wind component (m/s)</option>\
<option value="v"             >S-N wind component (m/s)</option>\
<option value="zradius"       >distance to planet centre (m)</option>\
<option value="zsphere"       >Altitude above the 6051km reference sphere (m)</option>\
<option value="zsurface"      >Altitude above local surface (m)</option>\
<option value="oroheight"     >Orographic height (m)</option>\
<option value="oro_gcm"       >Low resolution Orographic height (m)</option>\
<option value="ls"            >Solar longitude of Venus (deg)</option>\
<option value="venusau"       >Sun-Venus distance (UA)</option>\
<option value="LTST"          >Local true solar time (Vhrs)</option>\
<option value="utime"         >Universal solar time (Vhrs)</option>\
<option value="solzenangle"   >Solar zenith angle (deg)</option>\
<option value="tsurf"         >Surface temperature (K)</option>\
<option value="ps"            >Surface pressure (Pa)</option>\
<option value="rms_u"         >V-hourly variability (RMS) of zonal wind (m/s)</option>\
<option value="rms_v"         >V-hourly variability (RMS) of meridional wind (m/s)</option>\
<option value="rms_w"         >V-hourly variability (RMS) of vertical wind (m/s)</option>\
<option value="rms_t"         >V-hourly variability (RMS) of temperature (K)</option>\
<option value="rms_p"         >V-hourly variability (RMS) of pressure (Pa)</option>\
<option value="rms_rho"       >V-hourly variability (RMS) of density (kg/m3)</option>\
<option value="rms_tsurf"     >V-hourly variability (RMS) of surface temperature (K)</option>\
<option value="rms_ps"        >V-hourly variability (RMS) of the surface pressure (Pa)</option>\
<option value="dtd_u"         >Vday to Vday variability (RMS) of zonal wind (m/s)</option>\
<option value="dtd_v"         >Vday to Vday variability (RMS) of meridional wind (m/s)</option>\
<option value="dtd_w"         >Vday to Vday variability (RMS) of vertical wind (m/s)</option>\
<option value="dtd_t"         >Vday to Vday variability (RMS) of temperature (K)</option>\
<option value="dtd_p"         >Vday to Vday variability (RMS) of pressure (Pa)</option>\
<option value="dtd_rho"       >Vday to Vday variability (RMS) of density (kg/m3)</option>\
<option value="dtd_tsurf"     >Vday to Vday variability (RMS) of surface temperature (K)</option>\
<option value="dtd_ps"        >Vday to Vday variability (RMS) of surface pressure (Pa)</option>\
<option value="solar_flux_top">Net Solar Flux (SW) at top of the atmosphere (W/m2)</option>\
<option value="solar_flux_sw" >SW net flux (W/m2 pos. when downward)</option>\
<option value="solar_flux_lw" >LW net flux (W/m2 pos. when upward)</option>\
<option value="pscaleheight"  >Atmospheric scale height (m)</option>\
<option value="mean_mol_mass" >Atmospheric mean molar mass (g/mol)</option>\
<option value="cs"            >Atmospheric speed of sound cs (m/s)</option>\
<option value="r_gas"         >Atmospheric reduced molecular gas constant r (J/K/kg)</option>\
<option value="cp"            >Atmospheric heat capacity Cp (J/kg/K)</option>\
<option value="gamma"         >Atmospheric specific heat ratio (N/A)</option>\
<option value="viscosity"     >Atmospheric viscosity estimation (N/s/m2)</option>\
<option value="vmr_co2"       >CO2 volume mixing ratio (mol/mol)</option>\
<option value="vmr_co"        >CO volume mixing ratio (mol/mol)</option>\
<option value="vmr_o2"        >O2 volume mixing ratio (mol/mol)</option>\
<option value="vmr_o"         >O volume mixing ratio (mol/mol)</option>\
<option value="vmr_h"         >H volume mixing ratio (mol/mol)</option>\
<option value="vmr_h2"        >H2 volume mixing ratio (mol/mol)</option>\
<option value="vmr_h2o"       >H2O volume mixing ratio (mol/mol)</option>\
<option value="vmr_so2"       >SO2 volume mixing ratio (mol/mol)</option>\
<option value="vmr_so"        >SO volume mixing ratio (mol/mol)</option>\
<option value="vmr_ocs"       >OCS volume mixing ratio (mol/mol)</option>\
<option value="vmr_o3"        >O3 volume mixing ratio (mol/mol)</option>\
<option value="vmr_hcl"       >HCl volume mixing ratio (mol/mol)</option>\
<option value="vmr_n2"        >N2 volume mixing ratio (mol/mol)</option>\
<option value="vmr_he"        >He volume mixing ratio (mol/mol)</option>\
<option value="col_co2"       >CO2 column (kg/m2)</option>\
<option value="col_co"        >CO column (kg/m2)</option>\
<option value="col_o2"        >O2 column (kg/m2)</option>\
<option value="col_o"         >O column (kg/m2)</option>\
<option value="col_h"         >H column (kg/m2)</option>\
<option value="col_h2"        >H2 column (kg/m2)</option>\
<option value="col_h2o"       >H2O column (kg/m2)</option>\
<option value="col_so2"       >SO2 column (kg/m2)</option>\
<option value="col_so"        >SO column (kg/m2)</option>\
<option value="col_ocs"       >OCS column (kg/m2)</option>\
<option value="col_o3"        >O3 column (kg/m2)</option>\
<option value="col_hcl"       >HCl column (kg/m2)</option>\
<option value="col_n2"        >N2 column (kg/m2)</option>\
<option value="col_he"        >He column (kg/m2)</option>\
<option value="o2_ng"         >Vertically integrated O2 nightglow (MR)</option>\
<option value="vira_temp"     >VIRA model temperature (K)</option>\
<option value="vira_pres"     >VIRA model pressure (Pa)</option>\
<option value="vira_dens"     >VIRA model density (kg/m3)</option>\
');
